name: CI Pipeline for Push

on:
  push:
    branches:
      - master  # or master if that’s your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Git config (required for committing and pushing)
    - name: Set up Git
      run: |
        git config --global user.name "haqinzmamul12"
        git config --global user.email "haqinzmamul12@gmail.com"

    # Step 3: Make any changes or run build commands (optional)
    # Here, you can add steps to modify files or test them before committing changes.
    # For example:
    # - name: Run Tests
    #   run: python -m unittest discover

    # Step 4: Commit and push changes
    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Automated update from CI pipeline"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

